language: ruby
cache: bundler
rvm:
  - 2.5.1
script:
  - ./generate.sh
deploy:
  local-dir: gen
  repo: passepartoutvpn/api
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  keep-history: true
  on:
      branch: master #push-to-github
  target-branch: master #example
